CREATE TABLE `ct_book` (
`id` BIGINT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
`bk_name` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '书名',
`bk_url` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '书的链接',
`bk_img` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '书的首页图片',
`bk_hot_news` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '最新消息',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB AUTO_INCREMENT=222 DEFAULT CHARSET=utf8mb4;


CREATE TABLE `ct_job` (
`id` BIGINT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
`offset` INT(10) NOT NULL DEFAULT 0 COMMENT '偏移量',
`job_type` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '任务类型',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB AUTO_INCREMENT=123 DEFAULT CHARSET=utf8mb4;